/**
 * Vercel / CI: writes environment.prod.ts from BACKEND_URL before ng build.
 * BACKEND_URL = Railway public URL (no trailing slash), e.g. https://xxx.up.railway.app
 */
const fs = require('node:fs');
const path = require('node:path');

const backend = (process.env.BACKEND_URL ?? '').trim().replace(/\/+$/, '');
const apiUrl = backend ? `${backend}/api` : '/api';

const outFile = path.join(__dirname, 'src', 'environments', 'environment.prod.ts');
const content = `/** Auto-generated by set-env.js — do not edit manually on CI */
export const environment = {
  production: true,
  apiUrl: ${JSON.stringify(apiUrl)},
};
`;

fs.writeFileSync(outFile, content, 'utf8');
console.log(`[set-env] Wrote ${outFile}`);
console.log(`[set-env] apiUrl → ${apiUrl}`);

if (!backend) {
  console.warn(
    '[set-env] BACKEND_URL is not set. Using /api (local proxy). Set BACKEND_URL on Vercel Production.',
  );
}
